version: "3.6"

services:
  payone-billing-service-go:
    build: .
    container_name: payone-billing-service-go
    networks:
      - p1devnet
    restart: always
    ports:
      - "8086:8086"
    environment:
      MONGO_DSN: "mongodb://payone-mongo:27017/p1payapi"
      MONGO_DIAL_TIMEOUT: "10"
      CENTRIFUGO_SECRET: "secret"
      CARD_PAY_API_URL: "https://sandbox.cardpay.com"
      BROKER_ADDRESS: "amqp://rabbitmq:5672"
      MICRO_REGISTRY: consul
      MICRO_REGISTRY_ADDRESS: consul
    tty: true

  payone-billing-service-redis:
    image: redis:5.0.3
    container_name: payone-billing-service-redis
    restart: unless-stopped
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - p1devnet
    volumes:
      - payone-billing-service-redis:/data/redis

  payone-billing-service-redis-cluster:
    image: grokzen/redis-cluster
    container_name: payone-billing-service-redis-cluster
    restart: always
    environment:
      IP: "0.0.0.0"
    networks:
      - p1devnet
    ports:
      - '7000-7007:7000-7007'
      - '5000-5002:5000-5002'

volumes:
  payone-billing-service-redis:
    external: true

networks:
  p1devnet:
    external: true